plans/urls.py
from django.urls import path
from plans import views

urlpatterns = [
    path(
        route="subscription/cancel",
        view=views.CancelSubscriptionView.as_view(),
        name='cancel_subscription'),
    path(
        route="subscription/subscribe",
        view=views.CreateSubscriptionView.as_view(),
        name='create_subscription')
]

platzi_test/urls.py
from django.contrib import admin
from django.urls import path, include

from webhooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('users/', 
        include(('profiles.urls', 'profiles'), 
        namespace='profiles')),

    path('plans/', 
        include(('plans.urls', 'plans'), 
        namespace='plans')),

    path('stripe/webhooks/', 
        views.webhook_dispatcher,
        name="webhook-dispatcher")
]

profiles/urls.py
from django.urls import path
from profiles import views

urlpatterns = [
    path(
        route='login/',
        view=views.LoginUserView.as_view(),
        name='login'),

    path(
        route='logout/',
        view=views.LogoutUserView.as_view(),
        name='logout'),

    path(
        route='signup/',
        view=views.SignupUserView.as_view(),
        name='signup'),


    path(
        route='me',
        view=views.MeProfileView.as_view(),
        name='me_profile'),

    path(
        route='profile/update',
        view=views.UpdateProfileView.as_view(),
        name='update'),

    path(
        route='<str:username>/',
        view=views.DetailProfileView.as_view(),
        name='detail')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8"> {% block head_content %}{% endblock %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
		    crossorigin="anonymous">
	</head>

	<body>
		{% include "nav.html" %}
		<div class="container mt-5">
			{% block container %} {% endblock %}
		</div>
	</body>

	</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Navbar</a>
	<ul class="navbar-nav">
		<li class="nav-item active">
			<a class="nav-link" href="{% url "profiles:logout" %}">Logout</a>
	</ul>
</nav>