plans/urls.py
from django.urls import path
from plans import views

urlpatterns = [
    path(
        route="subscription/cancel",
        view=views.CancelSubscriptionView.as_view(),
        name='cancel_subscription'),
    path(
        route="subscription/subscribe",
        view=views.CreateSubscriptionView.as_view(),
        name='create_subscription')
]

platzi_test/urls.py
from django.contrib import admin
from django.urls import path, include

from webhooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('users/', 
        include(('profiles.urls', 'profiles'), 
        namespace='profiles')),

    path('plans/', 
        include(('plans.urls', 'plans'), 
        namespace='plans')),

    path('stripe/webhooks/', 
        views.webhook_dispatcher,
        name="webhook-dispatcher")
]

profiles/urls.py
from django.urls import path
from profiles import views

urlpatterns = [
    path(
        route='login/',
        view=views.LoginUserView.as_view(),
        name='login'),

    path(
        route='logout/',
        view=views.LogoutUserView.as_view(),
        name='logout'),

    path(
        route='signup/',
        view=views.SignupUserView.as_view(),
        name='signup'),


    path(
        route='me',
        view=views.MeProfileView.as_view(),
        name='me_profile'),

    path(
        route='profile/update',
        view=views.UpdateProfileView.as_view(),
        name='update'),

    path(
        route='<str:username>/',
        view=views.DetailProfileView.as_view(),
        name='detail')
]

profiles/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.CharField(max_length=150, null=True)
    phone_number = models.CharField(max_length=10, null=True)
    stripe_user_id = models.CharField(max_length=20, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

profiles/forms.py
import stripe

from django import forms
from django.conf import settings
from django.contrib.auth.models import User

from .models import Profile



class SignupForm(forms.Form):

    username = forms.CharField(
        max_length=150,
        required=True)

    password = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput())

    password_confirmation = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput())

    first_name = forms.CharField(
        max_length=150,
        required=True)
    last_name = forms.CharField(
        max_length=150,
        required=True)

    email = forms.CharField(
        max_length=150,
        required=True)

    website = forms.CharField(
        max_length=150,
        required=True)

    phone_number = forms.CharField(
        max_length=10,
        required=True)

    stripe_token = forms.CharField(
        max_length=30,
        widget=forms.HiddenInput())

    def clean_username(self):

        username = self.cleaned_data["username"]

        username_exists = (
            User
            .objects
            .filter(username=username)
            .exists())

        if username_exists:
            raise forms.ValidationError("Username is alreade taken")

        return username

    def clean(self):
        data = super().clean()

        password = data["password"]
        password_confirmation = data["password_confirmation"]

        if password != password_confirmation:
            raise forms.ValidationError(
                "Password and Password confirmation does not match")

        return data

    def save(self):
        data = self.cleaned_data

        data.pop("password_confirmation")

        user = User.objects.create_user(
            username=data["username"],
            first_name=data["first_name"],
            last_name=data["last_name"],
            password=data["password"],
            email=data["email"])

        stripe.api_key = settings.STRIPE_SECRET_KEY

        stripe_customer = stripe.Customer.create(
            source=data["stripe_token"],
            email=data["email"])

        profile = Profile(
            user=user,
            website=data["website"],
            phone_number=data["phone_number"],
            stripe_user_id=stripe_customer.id)

        profile.save()

profiles/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import TemplateView, UpdateView, FormView
from django.views.generic.detail import DetailView

from plans.models import Subscription, Plan

from .models import Profile
from .forms import SignupForm


# Create your views here.

class LoginUserView(LoginView):
    template_name = "users/login.html"


class LogoutUserView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy("profiles:login")


class SignupUserView(FormView):
    form_class = SignupForm
    template_name = "users/signup.html"
    success_url = reverse_lazy("profiles:login")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = "users/update.html"
    model = Profile
    fields = ["website", "phone_number"]

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        useraname = self.request.user.username
        return reverse_lazy("profiles.detail", {"username": useraname})


class DetailProfileView(LoginRequiredMixin, DetailView):
    slug_field = "username"
    slug_url_kwarg = "username"
    queryset = User.objects.all()
    template_name = "users/profile.html"
    context_object_name = "user"


class MeProfileView(LoginRequiredMixin, TemplateView):
    template_name = "users/me.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile

        subscription_count = Subscription.objects.filter(
            profile__user__username=self.request.user.username,
            is_active=True
        ).count()

        if subscription_count > 0:
            subscription = Subscription.objects.filter(
                profile__user__username=self.request.user.username,
                is_active=True
            ).get()
        else:
            subscription = None

        context['subscription'] = subscription
        context['plans'] = Plan.objects.all()

        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

	<head>
			<meta charset="UTF-8">
			{% block head_content %}{% endblock %}
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
				crossorigin="anonymous">
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
	</head>

	<body class="h-100">
		<div class="container h-100">
			<div class="row h-100 justify-content-center align-items-center">
				<div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
					{% block container %}{% endblock%}
				</div>
			</div>
		</div>

		{% block scripts %}{% endblock scripts %}

	</body>

	</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block container %}
<form method="POST" action="{% url "profiles:login" %}">
	{% csrf_token %}

	<div class="form-group">
		<input class="form-control" type="text" placeholder="Username" name="username" />
	</div>
	<div class="form-group">
		<input class="form-control" type="password" placeholder="Password" name="password" />
	</div>
	<button type="submit" class="btn btn-primary btn-block mt-5">
		Sign in
	</button>
	<div class="form-group">
		<a href="{% url 'profiles:signup' %}">Sign up!</a>
	</div>

</form>
{% endblock %}

templates/users/me.html
{% extends "base.html" %}

{% block container %}
	{% if messages %}
	<div class="alert alert-success">
		{% for message in messages %}
			{{ message }}
		{% endfor %}
	</div>
	{% endif %}
	<h1>Hola {{ user.username }}</h1>

	<div class="container">
		<h2>Plan activo</h2>
		{% if subscription %}
			<h3>
				{{subscription.plan.description}}
			</h3>
		{% else %}
			<h3>No tienes plan activo</h3>
		{% endif %}
		<form action="{% url "plans:cancel_subscription" %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="subscription_id" value="{{subscription.stripe_subscription_id}}">
			<button type="submit">Cancel Subscription</button>
		</form>
	</div>

<div class="container mt-5 text-center">
	<div class="row">
		{% for plan in plans %}
			<div class="col-xs-12 col-md-6">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h3 class="panel-title">
							{{plan.description}}
						</h3>
					</div>
					<div class="panel-body">
						<div class="the-price">
							<h1>
								${{plan.price}}
								<span class="subscript">{% if plan.is_annual %}
								/year
								{% else %}
								/month
								{% endif %}</span>
							</h1>
						</div>
						<table class="table">
							<tr>
								<td>
									2 Account
								</td>
							</tr>
							<tr class="active">
								<td>
									5 Project
								</td>
							</tr>
							<tr>
								<td>
									100K API Access
								</td>
							</tr>
							<tr class="active">
								<td>
									200MB Storage
								</td>
							</tr>
							<tr>
								<td>
									Custom Cloud Services
								</td>
							</tr>
							<tr class="active">
								<td>
									Weekly Reports
								</td>
							</tr>
						</table>
					</div>
					<div class="panel-footer">
						<form action="{% url "plans:create_subscription" %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="plan_id" value={{plan.stripe_plan_id}}>
							<button class="btn btn-info">Subscribe</button>
						</form>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>
{% endblock container %}

templates/users/profile.html
{% extends "base.html" %}

{% block container %}
	<h1>@{{ user.username }}</h1>
{% endblock container %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block container %}
	{% if error %}
		<p class="alert alert-danger">{{ error }}</p>
	{% endif%}
	<form id="register-form" method="POST" action="{% url "profiles:signup" %}">
		{% csrf_token %}

		{{form.as_p}}

		<label for="card-element">
			Credit or debit card
		</label>
		<div id="card-element"></div>

		<div id="card-errors" role="alert"></div>
		
		<button type="submit" class="btn btn-primary btn-block mt-5">
			Sign up!
		</button>

	</form>

{% endblock container %}

{% block scripts %}

	<script src="https://js.stripe.com/v3/"></script>

	<script>
		var stripe = Stripe('pk_test_KdNALPjOjWW7nfvvg1n1JK0u'); 
		var elements = stripe.elements();
 		var style = { 
			base: { 
				fontSize: '16px', 
				color: "#32325d", 
			} 
		};
		var card = elements.create('card', {style: style}); 
		card.mount('#card-element');

		var form = document.getElementById('register-form');
		form.addEventListener('submit', function(event) { 
			 event.preventDefault();
			stripe.createToken(card).then(function(result) { 
				if (result.error) {
					errorElement = document.getElementById('card-errors'); 
					errorElement.textContent = result.error.message; 
				} else {
					stripeTokenHandler(result.token); 
				} 
			});
		});

		function stripeTokenHandler(token) {
			var form = document.getElementById('register-form'); 
			var hiddenInput = document.createElement('input'); 
			hiddenInput.setAttribute('type','hidden'); 
			hiddenInput.setAttribute('name', 'stripe_token'); 
			hiddenInput.setAttribute('value', token.id); 
			form.appendChild(hiddenInput);
			form.submit();
		}

	</script>


{% endblock scripts %}

templates/users/update.html
{% extends "base.html" %}

{% block container %}
<div class="container">

	<div class="row justify-content-md-center">
		<div class="col-6 p-4" id="profile-box">

			<form action="{% url 'profiles:update' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %} 

				<div class="form-group">
					<label>Website</label>
					<input class="form-control" type="url" name="website" placeholder="Website" value="{{ profile.website }}" />
				</div>

				<div class="form-group">
					<label>Phone number</label>
					<input class="form-control" type="text" name="phone_number" placeholder="Phone number" value="{{ profile.phone_number }}"
					/>
				</div>

				<button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
			</form>
		</div>
	</div>
</div>
{% endblock container %}